// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsconnectAPI.Data;

#nullable disable

namespace SportsconnectAPI.Migrations
{
    [DbContext(typeof(SportsConnectDBContext))]
    [Migration("20230613031829_seventh")]
    partial class seventh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsconnectAPI.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pCode")
                        .HasColumnType("int");

                    b.Property<string>("playersAttending")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ea555fc-de84-43ad-b006-2522e80a3d9b"),
                            duration = 2,
                            location = "Port of Spain",
                            owner = "12970",
                            pCode = 15774,
                            playersAttending = "12971",
                            sport = "Soccer",
                            startDate = new DateTime(2023, 6, 12, 23, 18, 28, 994, DateTimeKind.Local).AddTicks(5890),
                            title = "Soccer Meet"
                        },
                        new
                        {
                            Id = new Guid("de7f893d-f00b-4b04-be1b-9b7b94d0dcd1"),
                            duration = 2,
                            location = "Port of Spain",
                            owner = "12973",
                            pCode = 15775,
                            playersAttending = "12971",
                            sport = "Soccer",
                            startDate = new DateTime(2023, 6, 12, 23, 18, 28, 994, DateTimeKind.Local).AddTicks(5895),
                            title = "Soccer Match"
                        },
                        new
                        {
                            Id = new Guid("6440efa8-d9fd-4bde-afb6-88a8bf821405"),
                            duration = 2,
                            location = "Port of Spain",
                            owner = "12971",
                            pCode = 15773,
                            playersAttending = "12970",
                            sport = "Soccer",
                            startDate = new DateTime(2023, 6, 12, 23, 18, 28, 994, DateTimeKind.Local).AddTicks(5898),
                            title = "SoccerMeet Game"
                        });
                });

            modelBuilder.Entity("SportsconnectAPI.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("attending")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("lastActive")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pCode")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c007e7ea-4932-4387-80c6-71085fdeca74"),
                            address = "Shakespeare Avenue",
                            age = 17,
                            attending = "No Events",
                            lastActive = new DateTime(2023, 6, 12, 23, 18, 28, 994, DateTimeKind.Local).AddTicks(5642),
                            name = "William",
                            pCode = 12972,
                            phone = "8687375691",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("912f0ec4-27d5-4b44-8eaf-7067fcd609fa"),
                            address = "Woodbrook",
                            age = 19,
                            attending = "No Events",
                            lastActive = new DateTime(2023, 6, 12, 23, 18, 28, 994, DateTimeKind.Local).AddTicks(5662),
                            name = "Zaak",
                            pCode = 12976,
                            phone = "18687964097",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("c3ddd429-0c20-4ad9-8ce2-042b72856c49"),
                            address = "PortofSpain",
                            age = 34,
                            attending = "15773",
                            lastActive = new DateTime(2023, 6, 12, 23, 18, 28, 994, DateTimeKind.Local).AddTicks(5665),
                            name = "Cody",
                            pCode = 12970,
                            phone = "186879874097",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("534fe14d-c20f-4665-84b6-5056331c399c"),
                            address = "Down Town",
                            age = 34,
                            attending = "15775, 1573",
                            lastActive = new DateTime(2023, 6, 12, 23, 18, 28, 994, DateTimeKind.Local).AddTicks(5691),
                            name = "Micheal",
                            pCode = 12973,
                            phone = "1868732274097",
                            sport = "All"
                        },
                        new
                        {
                            Id = new Guid("e82a2f1a-b321-44a4-8308-206a3e4e6b8e"),
                            address = "San Juan",
                            age = 38,
                            attending = "15774, 1575, 15773",
                            lastActive = new DateTime(2023, 6, 12, 23, 18, 28, 994, DateTimeKind.Local).AddTicks(5695),
                            name = "Gervais",
                            pCode = 12971,
                            phone = "1868732274097",
                            sport = "Soccer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
