// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsconnectAPI.Data;

#nullable disable

namespace SportsconnectAPI.Migrations
{
    [DbContext(typeof(SportsConnectDBContext))]
    [Migration("20230613022012_fifth")]
    partial class fifth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsconnectAPI.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pCode")
                        .HasColumnType("int");

                    b.Property<string>("playersAttending")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9bb67e72-c57a-45ed-9b55-4249f76b5343"),
                            duration = 2,
                            location = "Port of Spain",
                            owner = "12970",
                            pCode = 15774,
                            playersAttending = "12971",
                            startDate = new DateTime(2023, 6, 12, 22, 20, 12, 196, DateTimeKind.Local).AddTicks(6350),
                            title = "SoccerMeet"
                        },
                        new
                        {
                            Id = new Guid("a4cc67c5-0245-4775-ad07-dee03d1d1a4b"),
                            duration = 2,
                            location = "Port of Spain",
                            owner = "12973",
                            pCode = 15775,
                            playersAttending = "12971",
                            startDate = new DateTime(2023, 6, 12, 22, 20, 12, 196, DateTimeKind.Local).AddTicks(6356),
                            title = "SoccerMeet2"
                        },
                        new
                        {
                            Id = new Guid("dcf20863-d2aa-460a-ae3d-ab6146e7d525"),
                            duration = 2,
                            location = "Port of Spain",
                            owner = "12971",
                            pCode = 15773,
                            playersAttending = "12970",
                            startDate = new DateTime(2023, 6, 12, 22, 20, 12, 196, DateTimeKind.Local).AddTicks(6360),
                            title = "SoccerMeet3"
                        });
                });

            modelBuilder.Entity("SportsconnectAPI.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("attending")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("lastActive")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pCode")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3375793-e1a4-4d5c-b28f-30992e215f8d"),
                            address = "Shakespeare Avenue",
                            age = 17,
                            attending = "No Events",
                            lastActive = new DateTime(2023, 6, 12, 22, 20, 12, 196, DateTimeKind.Local).AddTicks(6017),
                            name = "William",
                            pCode = 12972,
                            phone = "8687375691",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("9d2e87eb-3ed2-4d6c-a1a9-a08a31f77bb7"),
                            address = "Woodbrook",
                            age = 19,
                            attending = "No Events",
                            lastActive = new DateTime(2023, 6, 12, 22, 20, 12, 196, DateTimeKind.Local).AddTicks(6062),
                            name = "Zaak",
                            pCode = 12976,
                            phone = "18687964097",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("6497a6c9-c717-4ac8-ab2b-563aef7aab8c"),
                            address = "PortofSpain",
                            age = 34,
                            attending = "15774",
                            lastActive = new DateTime(2023, 6, 12, 22, 20, 12, 196, DateTimeKind.Local).AddTicks(6066),
                            name = "Cody",
                            pCode = 12970,
                            phone = "186879874097",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("90ab3ef8-2f54-4374-bb83-b8b9dd8d43fd"),
                            address = "Down Town",
                            age = 34,
                            attending = "15775, 1573",
                            lastActive = new DateTime(2023, 6, 12, 22, 20, 12, 196, DateTimeKind.Local).AddTicks(6069),
                            name = "Gervais",
                            pCode = 12973,
                            phone = "1868732274097",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("7dcef371-d430-416c-8f3c-d8549ee2dc2e"),
                            address = "San Juan",
                            age = 38,
                            attending = "15774, 1575, 15773",
                            lastActive = new DateTime(2023, 6, 12, 22, 20, 12, 196, DateTimeKind.Local).AddTicks(6073),
                            name = "Gervais",
                            pCode = 12971,
                            phone = "1868732274097",
                            sport = "Soccer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
