// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsconnectAPI.Data;

#nullable disable

namespace SportsconnectAPI.Migrations
{
    [DbContext(typeof(SportsConnectDBContext))]
    [Migration("20230613024701_sixth")]
    partial class sixth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsconnectAPI.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pCode")
                        .HasColumnType("int");

                    b.Property<string>("playersAttending")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("506e5933-2197-4be5-a25e-356a93a1bbad"),
                            duration = 2,
                            location = "Port of Spain",
                            owner = "12970",
                            pCode = 15774,
                            playersAttending = "12971",
                            sport = "Soccer",
                            startDate = new DateTime(2023, 6, 12, 22, 47, 1, 186, DateTimeKind.Local).AddTicks(3113),
                            title = "SoccerMeet"
                        },
                        new
                        {
                            Id = new Guid("14ee902d-5c0b-4b48-bdfc-c20beaa552b7"),
                            duration = 2,
                            location = "Port of Spain",
                            owner = "12973",
                            pCode = 15775,
                            playersAttending = "12971",
                            sport = "Soccer",
                            startDate = new DateTime(2023, 6, 12, 22, 47, 1, 186, DateTimeKind.Local).AddTicks(3118),
                            title = "SoccerMeet2"
                        },
                        new
                        {
                            Id = new Guid("e9d02596-c0bc-4e71-8a14-2cb6d9d8564e"),
                            duration = 2,
                            location = "Port of Spain",
                            owner = "12971",
                            pCode = 15773,
                            playersAttending = "12970",
                            sport = "Soccer",
                            startDate = new DateTime(2023, 6, 12, 22, 47, 1, 186, DateTimeKind.Local).AddTicks(3121),
                            title = "SoccerMeet3"
                        });
                });

            modelBuilder.Entity("SportsconnectAPI.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("attending")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("lastActive")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pCode")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sport")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e52f6997-fc74-4380-9f9d-6bf20c0d3b33"),
                            address = "Shakespeare Avenue",
                            age = 17,
                            attending = "No Events",
                            lastActive = new DateTime(2023, 6, 12, 22, 47, 1, 186, DateTimeKind.Local).AddTicks(2837),
                            name = "William",
                            pCode = 12972,
                            phone = "8687375691",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("2e4cbc95-74ac-4db4-b6f0-21bb2deb44e2"),
                            address = "Woodbrook",
                            age = 19,
                            attending = "No Events",
                            lastActive = new DateTime(2023, 6, 12, 22, 47, 1, 186, DateTimeKind.Local).AddTicks(2877),
                            name = "Zaak",
                            pCode = 12976,
                            phone = "18687964097",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("339cf9d4-6dec-42af-b67b-b184de53f4d7"),
                            address = "PortofSpain",
                            age = 34,
                            attending = "15774",
                            lastActive = new DateTime(2023, 6, 12, 22, 47, 1, 186, DateTimeKind.Local).AddTicks(2881),
                            name = "Cody",
                            pCode = 12970,
                            phone = "186879874097",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("2fd6d0c6-46f9-4b10-90af-d4491f32a869"),
                            address = "Down Town",
                            age = 34,
                            attending = "15775, 1573",
                            lastActive = new DateTime(2023, 6, 12, 22, 47, 1, 186, DateTimeKind.Local).AddTicks(2884),
                            name = "Gervais",
                            pCode = 12973,
                            phone = "1868732274097",
                            sport = "Soccer"
                        },
                        new
                        {
                            Id = new Guid("ad0d5e01-d838-4c88-bec3-2380108c6728"),
                            address = "San Juan",
                            age = 38,
                            attending = "15774, 1575, 15773",
                            lastActive = new DateTime(2023, 6, 12, 22, 47, 1, 186, DateTimeKind.Local).AddTicks(2909),
                            name = "Gervais",
                            pCode = 12971,
                            phone = "1868732274097",
                            sport = "Soccer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
